---
development:
  cloud_name: <%= Rails.application.credentials.cloudinary_name %>
  api_key: <%= Rails.application.credentials.cloudinary_key %>
  api_secret: <%= Rails.application.credentials.cloudinary_secret %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: <%= Rails.application.credentials.cloudinary_name %>
  api_key: <%= Rails.application.credentials.cloudinary_key %>
  api_secret: <%= Rails.application.credentials.cloudinary_secret %>
  enhance_image_tag: true
  static_image_support: true